### ISSUE TITLE
Error when try chat

### ISSUE THREAD

**Issue by rzaprianov** [You-OpenSource/You-Python#110]
## 🔬 How To Reproduce

1. Chat open with Python3 youdotcom

### Code sample

The error:

YouShell > chat
Enter a message: what is Earth diameter
Enter webdriver_path (press enter for none): 
Please wait...
KeyError: 'message'
YouShell > 

### Environment

* OS: Linux
* Python version, get it with: 3.9

```bash
python --version
```

**Comment by SilkePilon** [comment]
Thx for the bug report, will look into this an get back to you
