### ISSUE TITLE
cloudscraper.exceptions.CloudflareChallengeError

### ISSUE THREAD

**Issue by Nnley** [You-OpenSource/You-Python#130]
How to solve the problem?
Code:
search_result = Search.search_for('test')
Error:
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Comment by SilkePilon** [comment]
Hi there, this is sadly a limitation of the free open source library's the package depends on, there is no "paid" version bc this is using another package to access you.com.

Hope this helps!
