### ISSUE TITLE
{'message': 'cloudflare error', 'time': '18', 'status_code': 503}

### ISSUE THREAD

**Issue by dertefter** [You-OpenSource/You-Python#136]
## 🐛 Bug Report

{'message': 'cloudflare error', 'time': '18', 'status_code': 503}

## 🔬 How To Reproduce

1. Run Example Code of YouChat

### Code sample

from youdotcom import Chat # import all the classes

chat = Chat.send_message(message="Привет как дела?", api_key="") # send a message to YouChat. passing the message and your api key.

# you can get an api key form the site: https://api.betterapi.net/ (with is also made by me)

print(chat)  # returns the message and some other data

### Environment

* OS: Windows 11
* Python version: 3.9

**Comment by SilkePilon** [comment]
Hi there, thanks for the bug report. This has now been fixed!
