### ISSUE TITLE
Can't visit betterapi

### ISSUE THREAD

**Issue by EyuphanMandiraci** [You-OpenSource/You-Python#161]
Hello, i will get an API key from BetterAPI.net but i can't access to website

![image](https://user-images.githubusercontent.com/42548576/234178383-fae7c63c-e9d6-4e12-a9fc-d0a7b558b3f9.png)

**Comment by SilkePilon** [comment]
Hi there! There is currently a bug with the domain. You can go to https://api.betterapi.net/ in the meantime.


Hope this helps

**Comment by EyuphanMandiraci** [comment]
Thanks!
