### ISSUE TITLE
https://api.betterapi.net/ giving cloudflare error

### ISSUE THREAD

**Issue by Ari6435** [You-OpenSource/You-Python#251]
Error 1033
Ray ID: 7e50aeca09cf691b •
2023-07-11 11:24:54 UTC
Argo Tunnel error
What happened?
You've requested a page on a website (api.betterapi.net) that is on the Cloudflare network. The host (api.betterapi.net) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.[
![Screenshot_20230711-165615](https://github.com/You-OpenSource/You-Python/assets/126169773/d90c9961-871e-4414-9ba5-5388b8f8b4a0)
](url)

**Comment by SilkePilon** [comment]
Working on this
