### ISSUE TITLE
Where to get api-key ?

### ISSUE THREAD

**Issue by svjack** [You-OpenSource/You-Python#38]
it seems ,In version 1.2.0 can use BETTERAPI_API_KEY to call you chat.
Where can I register to get it.

**Comment by SilkePilon** [comment]
Hi there you can get an api key on my new site: https://api.betterapi.net/

**Comment by SilkePilon** [comment]
Im planning to update all the code to work a lot faster and switch to using you.com api

**Comment by SilkePilon** [comment]
You can also use the api in any other programming language.
