### ISSUE TITLE
Error 1033 Argo Tunnel error

### ISSUE THREAD

**Issue by cateyelow** [You-OpenSource/You-Python#41]
![image](https://user-images.githubusercontent.com/73046218/217153823-33523e32-0930-470c-8691-040776f1dc3e.png)

**Comment by SilkePilon** [comment]
Sorry for the downtime. Api should be up and running again. Im working on adding load balancing

**Comment by SilkePilon** [comment]
Ima also working on a context system and an way to keep the chat and save the chat state
