### ISSUE TITLE
Number of requests allowed

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [You-OpenSource/You-Python#48]
Hello,

Thanks for this nice API on You.com. 

Actually the number of requests allowed is 5 per minute. Will this number be increased in the future or are there any subscription API planned?

**Comment by SilkePilon** [comment]
I plan on setting it to 10 or maybe 15, maybe a subscription based system but I don't like making money of a other platform that isn't focused on making money

**Comment by SilkePilon** [comment]
What would you suggest as an limit?

**Comment by Matthieu-Tinycoaching** [comment]
I don't really know, for personal use I suppose that 15 per minute should be right.

I understand your point of view regarding the free platform You.com. But for professional use in applications, do you know if there are some plans?

**Comment by SilkePilon** [comment]
I can upgrade the server so i can increase the limit to 30 or 40 but the upkeep costs would be to much for a 15 year old. I will set the new rate limit to 15 for testing soon.

**Comment by SilkePilon** [comment]
Also the only "paid" thing that there is rn is a personalized api key by donating you can dm me for a custom key
