### ISSUE TITLE
Bug, either 2 languages or a request of more than 40-60 characters, with api

### ISSUE THREAD

**Issue by pokedim13** [You-OpenSource/You-Python#50]
Hi. Thank you for a good tool, it remains to finalize only. I found such a bug that when requesting any information in two languages, or a request of more than 40-60 characters (I did not find the exact limit), server restarting returns.., check the logs via the api. Thank you in advance. I read that you are going to make subscriptions. I'm counting times you.com it is not aimed at earning money, then it is desirable that the services created on its basis are also not for earning. To live either on donations, or by attracting investors (to fight off through advertising, or another way of monetization)

**Comment by SilkePilon** [comment]
Hi there thx for the bug report, I'm still going to school so I haven't had much time to develop the library and api. I will try to work on it today also I'm planning on making it open source.

**Comment by SilkePilon** [comment]
hi there! found this in the Cloudflare settings: 
Maximum Upload Size
The amount of data visitors can upload to your website in a single request.

its set to a max of 100MB and i can set it bigger without it costing more

will still search for an better fix tho
