### ISSUE TITLE
Ever since the "web" version started to require "sign up/in", the API does not work anymore.

### ISSUE THREAD

**Issue by thonic** [You-OpenSource/You-Python#66]
## 🔧 API Error Report

Ever since the "web" version started to require "sign up/in", the API does not work anymore.

## 🔬 How To Reproduce (url used)

What url dit you use: `f"https://api.betterapi.net/youdotcom/chat?message={message}&key={api_key}"`

with key from: https://api.betterapi.net/

**Comment by SilkePilon** [comment]
Hi there! I'm currently working on this issue. You can join the discord server for updates

**Comment by SilkePilon** [comment]
Also the you.com api does not require an account. I think they changed something now that apps are available in the chat page
