### ISSUE TITLE
Is this lib an official one ?

### ISSUE THREAD

**Issue by RockChinQ** [You-OpenSource/You-Python#76]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/silkepilon/youdotcom/issues?q=is%3Aissue).

## ❓ Question

Hello! I wonder if this is an official library or reverse engineering one?

**Comment by SilkePilon** [comment]
hi there! 
This is an official lib. But not made by the you.com devs. So it's reverse-engineered.

**Comment by RockChinQ** [comment]
I see, thank you for your reply!
