### ISSUE TITLE
{"error":"Error, not likly made by you: invisibility_of_element() missing 1 required positional argument: 'element'"}

### ISSUE THREAD

**Issue by David2265** [You-OpenSource/You-Python#82]
## 🔧 API Error Report

Trying to access to the youchat API. Got the api_key from better api but it seems having some error. The api return as title and below:

{"error":"Error, not likly made by you: invisibility_of_element() missing 1 required positional argument: 'element'"}

Not sure what is the missing element. 

Thanks in advance.

### Screenshots

![image](https://user-images.githubusercontent.com/126744051/223313687-34524570-bfee-4d5a-aa74-143c3c3878ef.png)

from youdotcom import Chat # import all the classes

chat = Chat.send_message(message="how is your day?", api_key="today_generated_key") # send a message to YouChat. passing the message and your api key.

print(chat)  # returns the message and some other data

## 📈 Expected behavior

API shall return as chat behaviour as Youchat.

## 📎 Additional context

Running on Mac OS M1 chip using Python 3.9.16

**Comment by SilkePilon** [comment]
Thanks for the bug report, will look into this problem

**Comment by David2265** [comment]
You're welcome :)  

Please let us know if you have the resolve the issue.

**Comment by SilkePilon** [comment]
Hi there David,

I found a better way to bypass cloudflare, I'm implementing it soon then these errors will be gone.

**Comment by David2265** [comment]
Cool cool! looking forward. 

Thank you so much.

**Comment by David2265** [comment]
Hi @SilkePilon 

It trigger the same error but no error message this time. 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/126744051/224220068-eaee0e53-8731-4d1f-8033-eb22a178f0a1.png">

Thanks,
Dav

**Comment by SilkePilon** [comment]
Hi there, I've implemented an new system and I'm still improving it. I hope that this bug will no longer exist when I'm done setting it up

**Comment by SilkePilon** [comment]
Oh I've just noticed that they blocked the api for everyone, it's not public anymore

**Comment by SilkePilon** [comment]
I'm going to look for a fix

**Comment by NEK-RA** [comment]
> Oh I've just noticed that they blocked the api for everyone, it's not public anymore

Youcom blocked?

**Comment by SilkePilon** [comment]
Not anymore the api works again, they fixed it

**Comment by NEK-RA** [comment]
@SilkePilon btw is there any community for these github packages? Kinda where can they be discussed or asked for questions. Not sure that "Issues" section is suitable for probably "basic" questions

**Comment by SilkePilon** [comment]
There is an discord server in the readme if you scroll a bit down to the bottom

**Comment by SilkePilon** [comment]
That's the place where i post updates

**Comment by NEK-RA** [comment]
Thanks and sorry that I didn't scrollled enough 😅

**Comment by David2265** [comment]
It is working on my side, Thanks @SilkePilon! 
Can't wait to explore more with it!
